---
output: github_document
bibliography: doc/diabetes_references.bib
---

# Diabetes Predictor
- 
- contributors: Heidi Ye, Gurdeepak Sidhu, Marc Sun, Kevin Shahnazari

Demo of a data analysis project for DSCI 522 (Data Science workflows); a course in the Master of Data Science program at the University of British Columbia.

## About
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(knitr)
library(kableExtra)
library(tidyverse)
```

Here we attempt to build a classification model using the k-nearest neighbours algorithm which can use breast cancer tumour image measurements to predict whether a newly discovered breast cancer tumour is benign (i.e., is not harmful and does not require treatment) or malignant (i.e., is harmful and requires treatment intervention). Our final classifier performed fairly well on an unseen test data set, with Cohen's Kappa score of `r round(model_quality$overall[2], 1)` and an overall accuracy calculated to be `r round(model_quality$overall[1], 2)`. On the `r sum(model_quality$table)` test data cases, it correctly predicted  `r model_quality$table[2, 2] + model_quality$table[1, 1]`. However it incorrectly predicted  `r model_quality$table[2, 1] + model_quality$table[1, 2]` cases, and importantly these cases were false negatives; predicting that a tumour is benign when in fact it is malignant. These kind of incorrect predictions could have a severly negative impact on a patients health outcome, thus we recommend continuing study to improve this prediction model before it is put into production in the clinic. 

The data set that was used in this project is of digitized breast cancer image features created by Dr. William H. Wolberg, W. Nick Street, and Olvi L. Mangasarian at the University of Wisconsin, Madison [@Streetetal].  It was sourced from the UCI Machine Learning Repository [@Dua2019] and can be found [here](https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+(Diagnostic)), specifically [this file](http://mlr.cs.umass.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data). Each row in the data set represents summary statistics from measurements of an image of a tumour sample, including the diagnosis (benign or malignant) and several other measurements (e.g., nucleus texture, perimeter, area, etc.). Diagnosis for each image was conducted by physicians. 

## Report
The final report can be found [here](https://ttimbers.github.io/breast_cancer_predictor/doc/breast_cancer_predict_report.html).

## Usage

To replicate the analysis, clone this GitHub repository, install the [dependencies](#dependencies) listed below, and run the following commands at the command line/terminal from the root directory of this project:

```
# download the data
python src/downloadData.py --file_path=https://archive.ics.uci.edu/ml/machine-learning-databases/00529/diabetes_data_upload.csv --saving_path=data/raw_data.csv

#run eda report
Rscript -e "rmarkdown::render('src/diabetes_eda.Rmd',output_format='github_document')"

# clean, pre-process data
python src/clean_data.py --file_path=data/raw_data.csv --saving_path=data/cleaned_data.csv

# Split data into 80% train, 20% test
python src/split_data.py --input_file_path=data/cleaned_data.csv --saving_path_train=data/train_data.csv --saving_path_test=data/test_data.csv --test_size=0.2

# create exploratory data analysis figure and write to file 
Rscript src/eda_diab.r --train=data/train_data.csv --out_dir=results/figures/

# tune model and output results
python src/model_train.py --train_data_path="data/train_data.csv" --test_data_path="data/test_data.csv" --save_dir_models="results/models/" --save_dir_results="results/model_scores/"


# model figures
Rscript src/model_figures.r --model=results/model_scores/ --save_figures=results/figures

# render final report
Rscript -e "rmarkdown::render('report/diabete_predict_report.Rmd', output_format = 'github_document') 
```

## Dependencies
- Python 3.8.3 and Python packages:
  - pandas==1.1.1
  - scikit-learn==0.23.2
  - docopt==0.6.2
  - matplotlib==3.3.3
- R version 3.6.1 and R packages:
  - knitr==1.26
  - docopt==0.7.1
  - tidyverse==1.3.0
  - ggridges==0.5.2
  - ggthemes==4.2.0
  - ggplot2==3.3.2
  - stringr==1.4.0
  
## License
The Breast Cancer Predictor materials here are licensed under the Creative Commons Attribution 2.5 Canada License (CC BY 2.5 CA). If re-using/re-mixing please provide attribution and link to this webpage.

# References
